### ISSUE TITLE
[SUGGESTION] fix the example cpp code

### ISSUE THREAD

**Issue by nkxxll** [lsegal/cppgo#3]
The example C++ code for the library is not that great to be honest. 
I would be happy to fix it if I get an good example to work.

What I mean with not that great is that e.g. `sprintf` don't return a `char *` thus the code does not compile at all.

**Comment by lsegal** [comment]
Yes, the example was not focused on the C++ code (assuming you already have this in place), but there were some issues with the Go code as well, this is all fixed now.

**Comment by nkxxll** [comment]
Thanks a lot. <3
